#pragma once

#include <sb_base/base.h>

#define SB_CTF_ERROR_FACILITY SB_ENABLED
#define SB_CTF_LOG_FACILITY SB_ENABLED

#define SB_HASHSTR_POLICY_CRC 1
#define SB_HASHSTR_POLICY_FNV1A 2
#define SB_CTV_HASHSTR_POLICY SB_HASHSTR_POLICY_FNV1A
