#pragma once

#include <sb_core/core.h>

#define SB_CTF_ERROR_FACILITY SB_ENABLED
#define SB_CTF_LOG_FACILITY SB_ENABLED

#define SB_HASH_POLICY_CRC 1
#define SB_HASH_POLICY_FNV1A 2
#define SB_CTV_HASH_POLICY SB_HASH_POLICY_FNV1A

#define SB_HASH_SIZE_32BIT 1
#define SB_HASH_SIZE_64BIT 2
#define SB_CTV_HASH_SIZE SB_HASH_SIZE_64BIT
